//types para agregar productos
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO' 
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

//types para mostrar productos
export const INICIAR_DESCARGA_PRODUCTOS = 'INICIAR_DESCARGA_PRODUCTOS'
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO'
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR'

//types para eliminar productos
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO'
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR'