//types para agregar productos
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO' 
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

//types para mostrar productos
export const INICIAR_DESCARGA_PRODUCTOS = 'INICIAR_DESCARGA_PRODUCTOS'
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO'
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR'

//types para eliminar producto
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO'
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR'

//types para editar producto
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO'
export const INICIO_EDITAR_PRODUCTO = 'INICIO_EDITAR_PRODUCTO'
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO'
export const EDITAR_PRODUCTO_ERROR = 'EDITAR_PRODUCTO_ERROR'

//types para agregar usuario
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO' 
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO'
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR'